---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Instal YAML lint
  - pip install yamllint

  # Install Ansible-lint
  - pip install ansible-lint

script:
  # Check YAML syntax
  - yamllint .

  # Check the role/playbook's syntax.
  - ansible-lint .
